[project]
name = "dissociation"
version = "1.0.0"
description = "Dissociation of functional and representational similarity in deep neural networks."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jax>=0.4.29",
    "jaxlib>=0.4,<0.5",
]
